version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: tutoreng
      POSTGRES_PASSWORD: tutoreng-pass
      POSTGRES_DB: tutorneg
